# Generated by Django 4.1.1 on 2022-09-16 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='address_1',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='address_2',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='city',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='email',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='martial_status',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='state',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='years_present',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='zipcode',
        ),
    ]
